name: flutter_application_1
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  pdf: ^3.10.4
  path_provider: ^2.1.1
  open_file: ^3.1.0
  cupertino_icons: ^1.0.2
  flutter_downloader: ^1.6.1
  share_plus: ^2.0.4
  excel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/fonts/Roboto-Medium.ttf